blank_issues_enabled: false
contact_links:
  - name: Pixel Universe Feedback
    url: https://github.com/multiversogames/pixel-universe/discussions
    about: Share your feedback with the Pixel Universe team.
